services:
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - /data/service_data/synapse/data:/data
    depends_on:
      - db
    ports:
      - 127.0.0.1:${SYNAPSE_PORT}:8008/tcp
    networks:
      - synapse
    logging:
      options:
        max-size: "10m"

  db:
    image: docker.io/postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${SYNAPSE_DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /data/service_data/synapse/db:/var/lib/postgresql/data
    networks:
      - synapse
    logging:
      options:
        max-size: "10m"

networks:
  synapse:
    driver: bridge
