services:
  actual-mcp:
    image: sstefanov/actual-mcp:latest
    container_name: actual-mcp
    ports:
      - 0.0.0.0:${ACTUAL_MCP_PORT}:3000
    environment:
      - ACTUAL_SERVER_URL=${ACTUAL_SERVER_URL}
      - ACTUAL_PASSWORD=${ACTUAL_PASSWORD}
      - ACTUAL_BUDGET_SYNC_ID=${ACTUAL_BUDGET_SYNC_ID}
    command: --sse --enable-write
    restart: unless-stopped
