services:
  tuwunel:
    image: ghcr.io/matrix-construct/tuwunel:latest
    container_name: tuwunel
    restart: unless-stopped
    ports:
      - 127.0.0.1:${TUWUNEL_PORT}:8008
    volumes:
      - /data/service_data/tuwunel/data:/var/lib/tuwunel
    environment:
      - TUWUNEL_SERVER_NAME=${TUWUNEL_SERVER_NAME}
      - TUWUNEL_DATABASE_PATH=/var/lib/tuwunel
      - TUWUNEL_ALLOW_REGISTRATION=false
      - TUWUNEL_ALLOW_FEDERATION=true
      - TUWUNEL_ADDRESS=0.0.0.0
