services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: airtrail
      POSTGRES_USER: airtrail
      POSTGRES_PASSWORD: REDACTED_AIRTRAIL_DB_PASSWORD
      ORIGINS: http://zeus:8008,https://airtrail.example.com
      DB_URL: postgres://airtrail:REDACTED_AIRTRAIL_DB_PASSWORD@db:5432/airtrail
    volumes:
      - /data/service_data/airtrail/data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U airtrail -d airtrail']
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: unless-stopped
    environment:
      ORIGINS: http://zeus:8008,https://airtrail.example.com
      DB_URL: postgres://airtrail:REDACTED_AIRTRAIL_DB_PASSWORD@db:5432/airtrail
      DB_PASSWORD: REDACTED_AIRTRAIL_DB_PASSWORD
      DB_DATABASE_NAME: airtrail
      DB_USERNAME: airtrail
    ports:
      - 127.0.0.1:${AIRTRAIL_PORT}:3000
    depends_on:
      db:
        condition: service_healthy