services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 127.0.0.1:${AUDIOBOOKSHELF_PORT}:80
    volumes:
      - /data/media/audiobooks:/audiobooks
      - /data/media/podcasts:/podcasts
      - /data/service_data/audiobookshelf/config:/config
      - /data/service_data/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Asia/Calcutta
