services:
  komga:
    image: gotson/komga:1.24.1
    container_name: komga
    volumes:
      - /data/service_data/komga/config:/config
      - /data/media/books:/data
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 127.0.0.1:${KOMGA_PORT}:25600
    restart: unless-stopped