services:
  actual:
    image: docker.io/actualbudget/actual-server:26.7.0
    container_name: actual
    ports:
      - 127.0.0.1:${ACTUAL_PORT}:5006
    volumes:
      - /data/service_data/actual/data:/data
    healthcheck:
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
