services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    restart: unless-stopped
    ports:
      - 127.0.0.1:${THELOUNGE_PORT}:9000
    volumes:
      - /data/service_data/thelounge:/var/opt/thelounge
    logging:
      options:
        max-size: "10m"
