version: "3.3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped

    network_mode: host
    volumes:
      - ./config/obsidian.example.com:/etc/nginx/sites-available/obsidian.example.com
      - ./config/obsidian.example.com:/etc/nginx/sites-enabled/obsidian.example.com
      - ./config/nginx.conf:/etc/nginx/nginx.conf
