services:
  cloudeflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

    command: tunnel run
    restart: unless-stopped
    network_mode: host
    