services:
    app:
        image: fireflyiii/core:latest
        hostname: app
        container_name: firefly_iii_core
        networks:
            - firefly_iii
        restart: always
        volumes:
            - /data/service_data/firefly/upload:/var/www/html/storage/upload
        env_file: .env
        environment:
            APP_KEY: ${FIREFLY_APP_KEY}
            DB_PASSWORD: ${FIREFLY_DB_PASSWORD}
            APP_URL: https://firefly.${BASE_DOMAIN}
        ports:
            - ${FIREFLY_PORT}:8080
        depends_on:
            - db

    db:
        image: mariadb:lts
        hostname: db
        container_name: firefly_iii_db
        networks:
            - firefly_iii
        restart: always
        env_file: .db.env
        environment:
            MYSQL_PASSWORD: ${FIREFLY_DB_PASSWORD}
        volumes:
            - /data/service_data/firefly/mysql:/var/lib/mysql

    importer:
        image: fireflyiii/data-importer:latest
        hostname: importer
        restart: always
        container_name: firefly_iii_importer
        networks:
            - firefly_iii
        ports:
            - ${FIREFLY_IMPORTER_PORT}:8080
        depends_on:
            - app
        env_file: .importer.env
        environment:
            - VANITY_URL=http://localhost:${FIREFLY_PORT}

    cron:
        #
        # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
        # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
        #
        image: alpine
        container_name: firefly_iii_cron
        restart: always
        command: sh -c " apk add tzdata && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME;echo\" | crontab - && crond -f -L /dev/stdout"
        networks:
            - firefly_iii

networks:
    firefly_iii:
        driver: bridge
