services:
  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    ports:
      - 127.0.0.1:${DELUGE_PORT}:8112
      - 6881:6881
      - 6881:6881/udp
      - 127.0.0.1:58846:58846 #optional
    volumes:
      - /data/service_data/deluge/config:/config
      - /data/service_data/deluge/downloads:/downloads
