services:
  couchdb-main:
    container_name: couchdb-main
    image: obsidian-couchdb:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      SERVER_URL: http://obsidian.${BASE_DOMAIN}
      COUCHDB_USER: ${OBSIDIAN_COUCHDB_USER}
      COUCHDB_PASSWORD: ${OBSIDIAN_COUCHDB_PASSWORD}
      COUCHDB_DATABASE: main
    ports:
      - 127.0.0.1:${OBSIDIAN_PORT}:5984
    volumes:
      - /data/service_data/obsidian/couchdb-main:/opt/couchdb/data
      - /data/service_data/obsidian/couchdb-etc:/opt/couchdb/etc/local.d
