services:
  freshrss:
    image: freshrss/freshrss:1.26.3
    container_name: freshrss
    restart: unless-stopped
    ports:
      - ${FRESHRSS_PORT}:80
    environment:
      - TZ=Asia/Calcutta
      - CRON_MIN=1,31
    volumes:
      - /data/service_data/freshrss/data:/var/www/FreshRSS/data
      - /data/service_data/freshrss/extensions:/var/www/FreshRSS/extensions
    logging:
      options:
        max-size: "10m"
