services:
  copyparty:
    image: copyparty/ac:latest
    container_name: copyparty
    restart: unless-stopped
    ports:
      - 127.0.0.1:${COPYPARTY_PORT}:3923
    volumes:
      - /data/files:/w
      - /data/media:/media
      - /data/service_data/copyparty/config:/cfg
      - ./copyparty.conf:/cfg/copyparty.conf:ro
    environment:
      - TZ=Asia/Calcutta
      - PRTY_NO_DB_LOCK=1
